### ISSUE TITLE
lifetime err

### ISSUE THREAD

**Issue by aresbit** [pdx-cs-rust/rust-course-notes#2]
fn fst<'a, 'b: 'a>(x: &'b u64, _y: &'a u64) -> &'b u64 {
    &x
}

fn main() {
    let x = 7;
    {
        let y = 2;
        println!("{}", *fst(&x, &y));
    }
    println!("{}", *fst(&x, &2));
}

**Comment by BartMassey** [comment]
The code you quote:

```rust
fn fst<'a, 'b: 'a>(x: &'b u64, _y: &'a u64) -> &'b u64 {
    &x
}

fn main() {
    let x = 7;
    {
        let y = 2;
        println!("{}", *fst(&x, &y));
    }
    println!("{}", *fst(&x, &2));
}
```

compiles and runs fine for me. It prints 7 twice.

I tried with 2015 Edition and it works fine there too. Any information you could give me to try to reproduce the problem would be appreciated.

**Comment by aresbit** [comment]
sorry, l mean 03-2 lifetime.md lifetime sytax exmple should fix :fn fst<'a, 'b: 'a>(x: &'a u64  --->  fn fst<'a, 'b: 'a>(x: &'b u64

**Comment by BartMassey** [comment]
Ah, yes. Fixed, thanks!
